### ISSUE TITLE
Automatically create victoria logs datasource based on PromxyServerGroup

### ISSUE THREAD

**Issue by gmlexx** [k0rdent/kof#43]
Watch PromxyServerGroup with
```
---
apiVersion: kof.k0rdent.mirantis.com/v1alpha1
kind: PromxyServerGroup
metadata:
  labels:
    app.kubernetes.io/name: promxy-operator
    k0rdent.mirantis.com/promxy-secret-name: kof-mothership-promxy-config
  name: promxyservergroup-sample
  namespace: kof
spec:
  cluster_name: storage0
  targets:
    - "vmauth.storage0.example.net:443"
  path_prefix: "/vm/select/0/prometheus/"
  scheme: https
  http_client:
    dial_timeout: "5s"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      credentials_secret_name: "storage-vmuser-credentials"
      username_key: "username"
      password_key: "password"
```

Then automatically create Grafana datasource with the values provided in kof-storage template
```
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  valuesFrom:
    - targetPath: "basicAuthUser"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.username_key }}
          name: {{ .auth.credentials_secret_name }}
    - targetPath: "secureJsonData.basicAuthPassword"
      valueFrom:
        secretKeyRef:
          key: {{ .auth.password_key }}
          name: {{ .auth.credentials_secret_name }}
  datasource:
    access: proxy
    isDefault: false
    name: {{ .name }}
    type: "victoriametrics-logs-datasource"
    url: {{ .url }}
    basicAuth: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  resyncPeriod: 5m
```
