### ISSUE TITLE
More StorageClass issues

### ISSUE THREAD

**Issue by p5ntangle** [k0rdent/kof#88]
When passing the global: storageClass: xx to the mothership, that same storageClass is forced onto the storage/regional clusters.
So if the Mothership cluster is using a AWS storage class, then that would be pushed to regional storage clusters even if they are on say azure.

This can be worked around in the Service template, but it is a fiddle as it has to be declared in multiple places.
```
serviceSpec:
    priority: 100
    services:
      - name: ingress-nginx
        namespace: ingress-nginx
        template: ingress-nginx-4-11-3
      - name: cert-manager
        namespace: cert-manager
        template: cert-manager-1-16-2
        values: |
          cert-manager:
            crds:
              enabled: true
      - name: kof-storage
        namespace: kof
        template: kof-storage-0-1-0
        values: |
          external-dns:
            enabled: true
            global:
              storageClass: managed-csi
          global:
            storageClass: managed-csi
          victoriametrics:
            vmauth:
              ingress:
                host: vmauth.project2a-storage01.kof.mirdemo.com
            security:
              username_key: username
              password_key: password
              credentials_secret_name: storage-vmuser-credentials
            global:
              storageClass: managed-csi
          grafana:
            ingress:
              host: grafana.project2a-storage01.kof.mirdemo.com
            security:
              credentials_secret_name: grafana-admin-credentials
            global:
              storageClass: managed-csi
          cert-manager:
            email: someone@somewhere.com
          global:
              storageClass: managed-csi
```
In addition the storage class itself needs to be created of course. (edited)
